server {
    listen 80;
    listen [::]:80;
    server_name tightbeam.ing;

    root /var/www/tightbeam.ing;
    index index.html;

    location = / {
        return 302 /docs/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
